const fs = require('fs');
let html = fs.readFileSync('/home/temisotis/Projetos/palmira-framework-v20/metodo-perfect/index.html', 'utf8');

const replacements = [
    // 1. Hero
    [
        `                <span class="hero-eyebrow">A Arte de Criar Essências</span>\n                <h1 class="hero-title">Transforme o Poder da <span class="text-accent">Natureza</span> em sua\n                    Independência</h1>`,
        `                <span class="hero-eyebrow">A Arte de Criar Essências</span>\n                <h1 class="hero-title">Transforme o Poder da <span class="text-accent">Natureza</span> em Autoconhecimento e Renda Extra</h1>`
    ],
    [
        `                        <span class="lote active">Lote 01</span>\n                        <span class="lote">Lote 02</span>\n                        <span class="lote">Lote 03</span>`,
        `                        <span class="lote active">Lote 1 – R$15</span>\n                        <span class="lote">Lote 2 – R$20</span>\n                        <span class="lote">Lote 3 – R$25</span>`
    ],
    [
        `                <p class="hero-description">Descubra como criar fragrâncias que curam e construa um negócio lucrativo\n                    com sua própria linha de perfumes naturais.</p>\n                <div class="hero-actions">\n                    <a href="#cadastro" class="btn btn-primary pulse-loop">Quero Começar Agora</a>\n                </div>`,
        `                <p class="hero-description">Participe de duas aulas ao vivo e receba 2 receitas exclusivas de perfumes terapêuticos para fazer em casa, mesmo que você esteja começando do zero.<br><br><strong>Dias 5 e 7 de abril – Ao vivo</strong></p>\n                <div class="hero-actions">\n                    <a href="#cadastro" class="btn btn-primary pulse-loop">Quero Garantir Minha Vaga</a>\n                </div>`
    ],
    // 2. Desafio
    [
        `            <div class="challenge-content text-center">\n                <h2 class="section-title">O Desafio do Artesanato de Valor</h2>\n                <div class="challenge-visual text-center">\n                    <!-- Espaço Vazio Intencional -->\n                </div>\n                <p class="section-text">O segredo não está apenas no talento, mas em um método que une tradição\n                    ancestral e ciência emocional. Se você busca mais do que um hobby, busca um propósito lucrativo.</p>\n                <div class="quote-wrapper">\n                    <p class="quote">"O saber não se separa do sentir."</p>\n                </div>\n            </div>`,
        `            <div class="challenge-content text-center">\n                <h2 class="section-title">O Desafio de Transformar Sensibilidade em Valor</h2>\n                <div class="challenge-visual text-center">\n                    <!-- Espaço Vazio Intencional -->\n                </div>\n                <p class="section-text">Muitas mulheres sentem o chamado das plantas, dos aromas, da natureza… Mas não sabem por onde começar.<br><br>Não é sobre ter “dom”. É sobre aprender um caminho claro, simples e aplicável.<br><br>Se você busca autoconhecimento ou uma renda extra com propósito, essa semana foi criada para você.</p>\n                <div class="quote-wrapper">\n                    <p class="quote">"O saber não se separa do sentir."</p>\n                </div>\n            </div>`
    ],
    // 3. Método
    [
        `            <div class="text-center">\n                <h2 class="section-title">Conheça o Método Perfect</h2>\n                <p class="section-subtitle">Um sistema completo que te leva do zero à maestria na criação de\n                    fragrâncias.</p>\n            </div>\n\n            <div class="horizontal-cards-grid">\n                <!-- Card 1 -->\n                <div class="bento-card">\n                    <div class="card-image-placeholder"></div>\n                    <div class="card-content">\n                        <h3>Criação de perfumes que impactam</h3>\n                        <p>Aprenda a evocar sentimentos e memórias através de acordes olfativos precisos.</p>\n                    </div>\n                </div>\n\n                <!-- Card 2 -->\n                <div class="bento-card">\n                    <div class="card-image-placeholder"></div>\n                    <div class="card-content">\n                        <h3>Conexão entre olfato e pessoa</h3>\n                        <p>Como traduzir a essência de uma pessoa em uma fragrância única.</p>\n                    </div>\n                </div>\n\n                <!-- Card 3 -->\n                <div class="bento-card">\n                    <div class="card-image-placeholder"></div>\n                    <div class="card-content">\n                        <h3>Ciência das Plantas</h3>\n                        <p>Tinturas, óleos essenciais e macerados com rigor técnico e alma.</p>\n                    </div>\n                </div>\n\n                <!-- Card 4 -->\n                <div class="bento-card">\n                    <div class="card-image-placeholder"></div>\n                    <div class="card-content">\n                        <h3>Alta Fixação e Valor</h3>\n                        <p>Produtos que competem com o mercado de luxo.</p>\n                    </div>\n                </div>\n            </div>`,
        `            <div class="text-center">\n                <h2 class="section-title">O Que Você Vai Aprender na Semana</h2>\n                <p class="section-subtitle">Um passo a passo prático para criar seus primeiros perfumes terapêuticos.</p>\n            </div>\n\n            <div class="horizontal-cards-grid">\n                <!-- Card 1 -->\n                <div class="bento-card">\n                    <div class="card-image-placeholder"></div>\n                    <div class="card-content">\n                        <h3>Receita 01 – Perfume de Equilíbrio Emocional</h3>\n                        <p>Aprenda a combinar notas aromáticas que promovem centramento e bem-estar.</p>\n                    </div>\n                </div>\n\n                <!-- Card 2 -->\n                <div class="bento-card">\n                    <div class="card-image-placeholder"></div>\n                    <div class="card-content">\n                        <h3>Receita 02 – Perfume de Prosperidade e Confiança</h3>\n                        <p>Uma fórmula pensada para ativar autoestima e presença.</p>\n                    </div>\n                </div>\n\n                <!-- Card 3 -->\n                <div class="bento-card">\n                    <div class="card-image-placeholder"></div>\n                    <div class="card-content">\n                        <h3>Fundamentos da Perfumaria Terapêutica</h3>\n                        <p>Entenda como unir intenção, plantas e técnica.</p>\n                    </div>\n                </div>\n\n                <!-- Card 4 -->\n                <div class="bento-card">\n                    <div class="card-image-placeholder"></div>\n                    <div class="card-content">\n                        <h3>Como Transformar em Renda Extra</h3>\n                        <p>Possibilidades reais de começar a vender artesanalmente.</p>\n                    </div>\n                </div>\n            </div>`
    ],
    // 4. Para quem
    [
        `            <div class="text-center">\n                <h2 class="section-title">Este é o seu caminho se você...</h2>\n            </div>\n            <div class="para-quem-cards">\n                <div class="pq-card">\n                    <i class="ph ph-briefcase"></i>\n                    <p>Deseja empreender no mercado de bem-estar e aromaterapia.</p>\n                </div>\n                <div class="pq-card">\n                    <i class="ph ph-wallet"></i>\n                    <p>Busca uma fonte de renda extra com propósito real.</p>\n                </div>\n                <div class="pq-card">\n                    <i class="ph ph-plant"></i>\n                    <p>É terapeuta ou apaixonada por plantas e quer ampliar seus resultados.</p>\n                </div>\n                <div class="pq-card">\n                    <i class="ph ph-heart"></i>\n                    <p>Sente que precisa reconectar sua essência com um trabalho gratificante.</p>\n                </div>\n            </div>`,
        `            <div class="text-center">\n                <h2 class="section-title">Essa Semana é Para Você Se…</h2>\n            </div>\n            <div class="para-quem-cards">\n                <div class="pq-card">\n                    <i class="ph ph-heart"></i>\n                    <p>Tem entre 30 e 50 anos e sente que quer algo com mais propósito</p>\n                </div>\n                <div class="pq-card">\n                    <i class="ph ph-plant"></i>\n                    <p>Busca autoconhecimento através das plantas</p>\n                </div>\n                <div class="pq-card">\n                    <i class="ph ph-wallet"></i>\n                    <p>Quer começar uma renda extra artesanal</p>\n                </div>\n                <div class="pq-card">\n                    <i class="ph ph-drop"></i>\n                    <p>Ama aromaterapia, mas nunca produziu um perfume</p>\n                </div>\n                <div class="pq-card">\n                    <i class="ph ph-magic-wand"></i>\n                    <p>Quer aprender algo novo de forma simples e prática</p>\n                </div>\n            </div>`
    ],
    // 5. Da essencia ao lucro
    [
        `            <div class="text-center">\n                <h2 class="section-title">Da Essência ao Lucro</h2>\n                <p class="section-subtitle">Um Cronograma Prático para sua Transformação</p>\n            </div>`,
        `            <div class="text-center">\n                <h2 class="section-title">Da Essência à Primeira Criação</h2>\n                <p class="section-subtitle">Um cronograma enxuto e direto:</p>\n            </div>`
    ],
    // 6. Beneficios
    [
        `            <div class="benefits-grid">\n                <div class="benefit-card">\n                    <i class="ph ph-trend-up"></i>\n                    <h3>Liberdade Financeira</h3>\n                    <p>Lucro real com produtos 100% autorais.</p>\n                </div>\n                <div class="benefit-card">\n                    <i class="ph ph-heart-half"></i>\n                    <h3>Bem-estar Profundo</h3>\n                    <p>Autonomia para criar curas através do olfato.</p>\n                </div>\n                <div class="benefit-card">\n                    <i class="ph ph-lightning"></i>\n                    <h3>Praticidade</h3>\n                    <p>Materiais exclusivos e aprendizado direto ao ponto.</p>\n                </div>\n            </div>`,
        `            <div class="benefits-grid">\n                <div class="benefit-card">\n                    <i class="ph ph-heart-half"></i>\n                    <h3>Autoconhecimento</h3>\n                    <p>Entenda emoções através dos aromas.</p>\n                </div>\n                <div class="benefit-card">\n                    <i class="ph ph-trend-up"></i>\n                    <h3>Possibilidade de Renda Extra</h3>\n                    <p>Comece pequeno, mas comece certo.</p>\n                </div>\n                <div class="benefit-card">\n                    <i class="ph ph-lightning"></i>\n                    <h3>Praticidade</h3>\n                    <p>Receitas aplicáveis com explicação simples.</p>\n                </div>\n            </div>`
    ],
    // 7. Mentora
    [
        `                        <span class="eyebrow">Quem Guia Você</span>\n                        <h2 class="title">Palmira Margarida</h2>\n                        <p class="bio">Palmira é especialista em alquimia emocional e criação de produtos botânicos\n                            autorais. Com mais de uma década unindo saberes ancestrais à ciência dos óleos e extratos,\n                            já ensinou milhares de alunas a transformarem sua sensibilidade em um modelo de negócio\n                            seguro, rentável e transformador.</p>\n                        <div class="quote-box">\n                            <p>"Minha missão é guiar você na construção da sua independência financeira fazendo o que\n                                sente de verdade."</p>\n                        </div>`,
        `                        <span class="eyebrow">Quem Guia Você</span>\n                        <h2 class="title">Palmira Margarida</h2>\n                        <p class="bio">Especialista em alquimia emocional e criação de produtos botânicos autorais.<br><br>Há mais de uma década ensina mulheres a transformarem sensibilidade em criação prática e possível.</p>\n                        <div class="quote-box">\n                            <p>"Toda mulher pode transformar essência em independência."</p>\n                        </div>`
    ],
    // 8. CTA Final
    [
        `        <div class="container narrow-container text-center">\n            <h2 class="cta-title">A Arte de Mudar Vidas está a um Passo de Você</h2>\n            <p class="cta-text">Sua sensibilidade, sua criatividade e sua independência financeira esperam por esse\n                método. Não deixe o seu propósito para depois.</p>\n            <div class="cta-actions">\n                <a href="#cadastro" class="btn btn-primary pulse-loop">Garantir Minha Vaga Agora</a>\n            </div>\n        </div>`,
        `        <div class="container narrow-container text-center">\n            <h2 class="cta-title">Sua Primeira Essência Começa Aqui</h2>\n            <p class="cta-text">Duas aulas.<br>Duas receitas.<br>Um novo caminho.<br><br>Garanta sua vaga antes da virada de lote.</p>\n            <div class="cta-actions">\n                <a href="#cadastro" class="btn btn-primary pulse-loop">Quero Participar da Semana Perfumaria Terapêutica</a>\n            </div>\n        </div>`
    ],
    // 9. Footer
    [
        `            <h3 class="footer-title">MÉTODO PERFECT</h3>\n            <p class="footer-copy">&copy; 2026 Palmira Margarida. Todos os direitos reservados.</p>`,
        `            <h3 class="footer-title">SEMANA PERFUMARIA TERAPÊUTICA</h3>\n            <p class="footer-copy">&copy; 2026 Palmira Margarida. Todos os direitos reservados.</p>`
    ]
];

replacements.forEach(([search, replace], index) => {
    if (html.includes(search)) {
        html = html.replace(search, replace);
        console.log(\`Replaced chunk \${index + 1}\`);
    } else {
        console.log(\`Could not find chunk \${index + 1}\`);
        console.log("Looking for:", JSON.stringify(search));
    }
});

fs.writeFileSync('/home/temisotis/Projetos/palmira-framework-v20/metodo-perfect/index.html', html);
console.log("Done");
